services:
  redis:
    image: redis/redis-stack:latest
    environment:
      - "REDIS_ARGS=--requirepass 12345678"
    ports:
      - 6379:6379
      - 8001:8001
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ".:/server"
      - "/server/node_modules"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis # Use service name discovered by DNS
    develop:
      watch:
        - action: sync
          path: ./src
          target: /server/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    command: npm run dev
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web
      - redis
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/default.conf
          target: /etc/nginx/conf.d/default.conf
