services:
  redis:
    image: redis/redis-stack:latest
    environment:
      - "REDIS_ARGS=--requirepass 12345678"
    ports:
      - 6379:6379
      - 8001:8001
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ".:/server"
      - "/server/node_modules"
    ports:
      - 5000:5000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis # Use service name discovered by DNS
    command: npm run dev
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web
      - redis
